<a href="https://colab.research.google.com/github/Sim-hub22/AI_Week1/blob/main/WORKSHEET_0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exercise on Functions:

Task - 1:

Create a Python program that converts between different units of measurement.

• The program should:
1. Prompt the user to choose the type of conversion (e.g., length, weight, volume).
2. Ask the user to input the value to be converted.
3. Perform the conversion and display the result.
4. Handle potential errors, such as invalid input or unsupported conversion types.


• Requirements:
1. Functions: Define at least one function to perform the conversion.
2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values).
3. User Input: Prompt the user to select the conversion type and input the value.
4. Docstrings: Include a docstring in your function to describe its purpose, parameters, and
return value.

• Conversion Options:
1. Length:
– Convert meters (m) to feet (ft).
– Convert feet (ft) to meters (m).
2. Weight:
– Convert kilograms (kg) to pounds (lbs).
– Convert pounds (lbs) to kilograms (kg).
3. Volume:
– Convert liters (L) to gallons (gal).
– Convert gallons (gal) to liters (L)

In [ ]:
def unit_converter():
    """
    Converts units between length, weight, and volume.

    User selects the conversion type and provides the value.
    Returns the converted value.

    Returns:
        float: converted result
    """

    print("Select Conversion Type:")
    print("1. Length")
    print("2. Weight")
    print("3. Volume")

    try:
        choice = int(input("Enter your choice (1-3): "))
        value = float(input("Enter value to convert: "))

        if choice == 1:
            print("1. Meters to Feet")
            print("2. Feet to Meters")
            sub = int(input("Select option: "))

            if sub == 1:
                result = value * 3.28084
                print(f"{value} meters = {result} feet")
            elif sub == 2:
                result = value / 3.28084
                print(f"{value} feet = {result} meters")
            else:
                print("Invalid option")

        elif choice == 2:
            print("1. Kilograms to Pounds")
            print("2. Pounds to Kilograms")
            sub = int(input("Select option: "))

            if sub == 1:
                result = value * 2.20462
                print(f"{value} kg = {result} lbs")
            elif sub == 2:
                result = value / 2.20462
                print(f"{value} lbs = {result} kg")
            else:
                print("Invalid option")

        elif choice == 3:
            print("1. Liters to Gallons")
            print("2. Gallons to Liters")
            sub = int(input("Select option: "))

            if sub == 1:
                result = value * 0.264172
                print(f"{value} L = {result} gallons")
            elif sub == 2:
                result = value / 0.264172
                print(f"{value} gallons = {result} L")
            else:
                print("Invalid option")

        else:
            print("Invalid conversion type")

    except ValueError:
        print("Invalid input. Please enter numeric values.")

unit_converter()

Select Conversion Type:
1. Length
2. Weight
3. Volume
Enter your choice (1-3): 1
Enter value to convert: 24
1. Meters to Feet
2. Feet to Meters
Select option: 1
24.0 meters = 78.74016 feet


Task - 2:

Create a Python program that performs various mathematical operations on a list of numbers.

• The Program should:
1. Prompt the user to choose an operation (e.g., find the sum, average, maximum, or minimum
of the numbers).
2. Ask the user to input a list of numbers (separated by spaces).
3. Perform the selected operation and display the result.
4. Handle potential errors, such as invalid input or empty lists.

• Requirements:
1. Functions: Define at least one function for each operation (sum, average, maximum, minimum).
2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values or
empty lists).
3. User Input: Prompt the user to select the operation and input the list of numbers.
4. Docstrings: Include a docstring in each function to describe its purpose, parameters, and
return value.


In [ ]:
def calculate_sum(numbers):
    """Return sum of numbers."""
    return sum(numbers)

def calculate_average(numbers):
    """Return average of numbers."""
    return sum(numbers) / len(numbers)

def find_max(numbers):
    """Return maximum value."""
    return max(numbers)

def find_min(numbers):
    """Return minimum value."""
    return min(numbers)


def math_operations():
    try:
        nums = input("Enter numbers separated by space: ")
        numbers = [float(x) for x in nums.split()]

        if len(numbers) == 0:
            raise ValueError("List cannot be empty")

        print("Choose Operation:")
        print("1. Sum")
        print("2. Average")
        print("3. Maximum")
        print("4. Minimum")

        choice = int(input("Enter choice: "))

        if choice == 1:
            print("Sum =", calculate_sum(numbers))
        elif choice == 2:
            print("Average =", calculate_average(numbers))
        elif choice == 3:
            print("Maximum =", find_max(numbers))
        elif choice == 4:
            print("Minimum =", find_min(numbers))
        else:
            print("Invalid choice")

    except ValueError:
        print("Invalid input.")

math_operations()

Enter numbers separated by space: 2 2
Choose Operation:
1. Sum
2. Average
3. Maximum
4. Minimum
Enter choice: 3
Maximum = 2.0


#Exercise on List Manipulation:

1. Extract Every Other Element:

    Write a Python function that extracts every other element from a list, starting from the first element.

    • Requirements:

    – Define a function extract every other(lst) that takes a list lst as input and returns a new list containing every other element from the original list.

    – Example: For the input [1, 2, 3, 4, 5, 6], the output should be [1, 3, 5]

In [ ]:
def extract_every_other(lst):
    return lst[::2]

lst = list(map(int, input("Enter numbers: ").split()))
result = extract_every_other(lst)

print("Every other element:", result)

Enter numbers: 1 2 3 4 5 6 7
Every other element: [1, 3, 5, 7]


2. Slice a Sublist:

    Write a Python function that returns a sublist from a given list, starting from a specified index and ending at another specified index.

    • Requirements:

    – Define a function get sublist(lst, start, end) that takes a list lst, a starting index start, and an ending index end as input and returns the sublist from start to end (inclusive).

    – Example: For the input [1, 2, 3, 4, 5, 6] with start=2 and end=4, the output should be [3, 4, 5].

In [ ]:
def get_sublist(lst, start, end):
    return lst[start:end+1]

lst = list(map(int, input("Enter numbers: ").split()))
start = int(input("Enter start index: "))
end = int(input("Enter end index: "))

result = get_sublist(lst, start, end)

print("Sublist:", result)

Enter numbers: 1 2 3 4 5
Enter start index: 1
Enter end index: 5
Sublist: [2, 3, 4, 5]


3. Reverse a List Using Slicing:

    Write a Python function that reverses a list using slicing.

    • Requirements:

    – Define a function reverse list(lst) that takes a list lst and returns a reversed list using
    slicing.

    – Example: For the input [1, 2, 3, 4, 5], the output should be [5, 4, 3, 2, 1].

In [ ]:
def reverse_list(lst):
    return lst[::-1]

lst = list(map(int, input("Enter numbers: ").split()))

result = reverse_list(lst)

print("Reversed list:", result)

Enter numbers: 1 2 3 4 5
Reversed list: [5, 4, 3, 2, 1]


4. Remove the First and Last Elements:

    Write a Python function that removes the first and last elements of a list and returns the resulting sublist.

    • Requirements:

    – Define a function remove first last(lst) that takes a list lst and returns a sublist without
    the first and last elements using slicing.

    – Example: For the input [1, 2, 3, 4, 5], the output should be [2, 3, 4].


In [ ]:
def remove_first_last(lst):
    return lst[1:-1]

lst = list(map(int, input("Enter numbers: ").split()))

result = remove_first_last(lst)

print("List without first and last:", result)

Enter numbers: 1 2 3 4 5
List without first and last: [2, 3, 4]


5. Get the First n Elements:

    Write a Python function that extracts the first n elements from a list.

    • Requirements:

    – Define a function get first n(lst, n) that takes a list lst and an integer n as input and
    returns the first n elements of the list using slicing.

    – Example: For the input [1, 2, 3, 4, 5] with n=3, the output should be [1, 2, 3].

In [ ]:
def get_first_n(lst, n):
    return lst[:n]

lst = list(map(int, input("Enter numbers: ").split()))
n = int(input("Enter value of n: "))

result = get_first_n(lst, n)

print("First n elements:", result)

Enter numbers: 1 2 3 4 
Enter value of n: 2
First n elements: [1, 2]


6. Extract Elements from the End:

    Write a Python function that extracts the last n elements of a list using slicing.

    • Requirements:

    – Define a function get last n(lst, n) that takes a list lst and an integer n as input and returns the last n elements of the list.

    – Example: For the input [1, 2, 3, 4, 5] with n=2, the output should be [4, 5].

In [ ]:
def get_last_n(lst, n):
    return lst[-n:]

lst = list(map(int, input("Enter numbers: ").split()))
n = int(input("Enter value of n: "))

result = get_last_n(lst, n)

print("Last n elements:", result)

Enter numbers: 1 2 3 4 5
Enter value of n: 3
Last n elements: [3, 4, 5]


7. Extract Elements in Reverse Order:

    Write a Python function that extracts a list of elements in reverse order starting from the second-to-last element and skipping one element in between.

    • Requirements:

    – Define a function reverse skip(lst) that takes a list lst and returns a new list containing every second element starting from the second-to-last, moving backward.

    – Example: For the input [1, 2, 3, 4, 5, 6], the output should be [5, 3, 1].


In [ ]:
def reverse_skip(lst):
    return lst[-2::-2]

lst = list(map(int, input("Enter numbers: ").split()))

result = reverse_skip(lst)

print("Reverse skip elements:", result)

Enter numbers: 1 2 3 4 5
Reverse skip elements: [4, 2]


#Exercise on Nested List:

1. Flatten a Nested List:

    Write a Python function that takes a nested list and flattens it into a single list, where all the elements are in a single dimension.

    • Requirements:

    – Define a function flatten(lst) that takes a nested list lst and returns a flattened version of the list.

    – Example: For the input [[1, 2], [3, 4], [5]], the output should be [1, 2, 3, 4, 5].

In [ ]:
def flatten(lst):
    flat = []
    for sub in lst:
        for item in sub:
            flat.append(item)
    return flat

lst = eval(input("Enter nested list: "))
print("Flattened list:", flatten(lst))

Enter nested list: [[1,2], [2,3], [3,4]]
Flattened list: [1, 2, 2, 3, 3, 4]


2. Accessing Nested List Elements:

    Write a Python function that extracts a specific element from a nested list given its indices.

    • Requirements:

    – Define a function access nested element(lst, indices) that takes a nested list lst and
    a list of indices indices, and returns the element at that position.

    – Example: For the input lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] with indices = [1,
    2], the output should be 6.


In [ ]:
def access_nested_element(lst, indices):
    element = lst
    for i in indices:
        element = element[i]
    return element


lst = eval(input("Enter nested list: "))
indices = eval(input("Enter indices list: "))

print("Element:", access_nested_element(lst, indices))\

Enter nested list: [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
Enter indices list: [1, 2]
Element: 6


3. Sum of All Elements in a Nested List:

    Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth).

    • Requirements:

    – Define a function sum nested(lst) that takes a nested list lst and returns the sum of all the elements.

    – Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 21.

In [ ]:
def sum_nested(lst):
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)
        else:
            total += item
    return total

lst = eval(input("Enter nested list: "))
print("Sum:", sum_nested(lst))

Enter nested list: [[1, 2], [3, [4, 5]], 6]
Sum: 21


4. Remove Specific Element from a Nested List:

    Write a Python function that removes all occurrences of a specific element from a nested list.

    • Requirements:

    – Define a function remove element(lst, elem) that removes elem from lst and returns the modified list.

    – Example: For the input lst = [[1, 2], [3, 2], [4, 5]] and elem = 2, the output should be [[1], [3], [4, 5]].


In [ ]:
def remove_element(lst, elem):
    result = []
    for item in lst:
        if isinstance(item, list):
            result.append(remove_element(item, elem))
        else:
            if item != elem:
                result.append(item)
    return result

lst = eval(input("Enter nested list: "))
elem = int(input("Enter element to remove: "))

print("Modified list:", remove_element(lst, elem))

Enter nested list: [[1, 2], [3, 2], [4, 5]]
Enter element to remove: 2
Modified list: [[1], [3], [4, 5]]


5. Find the Maximum Element in a Nested List:

    Write a Python function that finds the maximum element in a nested list (regardless of depth).

    • Requirements:

    – Define a function find max(lst) that takes a nested list lst and returns the maximum element.

    – Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 6.


In [ ]:
def find_max(lst):
    maximum = float('-inf')

    for item in lst:
        if isinstance(item, list):
            maximum = max(maximum, find_max(item))
        else:
            maximum = max(maximum, item)

    return maximum

lst = eval(input("Enter nested list: "))
print("Maximum element:", find_max(lst))

Enter nested list: [[1, 2], [3, [4, 5]], 6]
Maximum element: 6


6. Count Occurrences of an Element in a Nested List:

    Write a Python function that counts how many times a specific element appears in a nested list.

    • Requirements:

    – Define a function count occurrences(lst, elem) that counts the occurrences of elem in the nested list lst.

    – Example: For the input lst = [[1, 2], [2, 3], [2, 4]] and elem = 2, the output should be 3.


In [ ]:
def count_occurrences(lst, elem):
    count = 0

    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)
        elif item == elem:
            count += 1

    return count

lst = eval(input("Enter nested list: "))
elem = int(input("Enter element to count: "))

print("Occurrences:", count_occurrences(lst, elem))

Enter nested list:  [[1, 2], [2, 3], [2, 4]]
Enter element to count: 2
Occurrences: 3


7. Flatten a List of Lists of Lists:

    Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth.

    • Requirements:

    – Define a function deep flatten(lst) that takes a deeply nested list lst and returns a single flattened list.

    – Example: For the input [[[1, 2], [3, 4]], [[5, 6], [7, 8]]], the output should be [1, 2, 3, 4, 5, 6, 7, 8].

In [ ]:
def deep_flatten(lst):
    flat = []

    for item in lst:
        if isinstance(item, list):
            flat.extend(deep_flatten(item))
        else:
            flat.append(item)

    return flat

lst = eval(input("Enter nested list: "))
print("Flattened list:", deep_flatten(lst))

Enter nested list: [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
Flattened list: [1, 2, 3, 4, 5, 6, 7, 8]


8. Nested List Average:

    Write a Python function that calculates the average of all elements in a nested list.

    • Requirements:

    – Define a function average nested(lst) that takes a nested list lst and returns the average of all the elements.

    – Example: For the input [[1, 2], [3, 4], [5, 6]], the output should be 3.5.

In [ ]:
def average_nested(lst):

    def helper(lst):
        total = 0
        count = 0

        for item in lst:
            if isinstance(item, list):
                s, c = helper(item)
                total += s
                count += c
            else:
                total += item
                count += 1

        return total, count

    total, count = helper(lst)
    return total / count


lst = eval(input("Enter nested list: "))
print("Average:", average_nested(lst))

Enter nested list: [[1, 2], [3, 4], [5, 6]]
Average: 3.5


#Basic Vector and Matrix Operation with Numpy.

##Problem - 1: Array Creation:



In [2]:
import numpy as np

1. Initialize an empty array with size 2X2.

In [ ]:
arr1 = np.empty((2,2))
print(arr1)

[[3.53347365e-315 0.00000000e+000]
 [5.89473325e-091 2.61787239e+180]]


2. Initialize an all one array with size 4X2.


In [ ]:
arr2 = np.ones((4,2))
print(arr2)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


3. Return a new array of given shape and type, filled with fill value.

    {Hint: np.full}


In [3]:
arr = np.full((3,3), 8)
print(arr)

[[8 8 8]
 [8 8 8]
 [8 8 8]]


4. Return a new array of zeros with same shape and type as a given array.
  
    {Hint: np.zeros like}


In [ ]:
arr = np.zeros_like(arr2)
print(arr)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


5. Return a new array of ones with same shape and type as a given array.

    {Hint: np.ones like}


In [ ]:
arr5 = np.ones_like(arr1)
print(arr5)

[[1. 1.]
 [1. 1.]]


6. For an existing list new_list = [1,2,3,4] convert to an numpy array.

    {Hint: np.array()}


In [ ]:
new_list = [1,2,3,4]
arr6 = np.array(new_list)
print(arr6)

[1 2 3 4]


##Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:


1. Create an array with values ranging from 10 to 49.

    {Hint:np.arrange()}.


In [ ]:
a = np.arange(10,50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


2. Create a 3X3 matrix with values ranging from 0 to 8.

   {Hint:look for np.reshape()}


In [ ]:
b = np.arange(9).reshape(3,3)
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


3. Create a 3X3 identity matrix.

    {Hint:np.eye()}


In [ ]:
c = np.eye(3)
print(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


4. Create a random array of size 30 and find the mean of the array.

    {Hint:check for np.random.random() and array.mean() function}

In [ ]:
d = np.random.random(30)
print("Mean:", d.mean())

Mean: 0.5135813311683314


5. Create a 10X10 array with random values and find the minimum and maximum values.


In [ ]:
e = np.random.random((10,10))
print("Minimum:", e.min())
print("Maximum:", e.max())

Minimum: 0.003784339482799326
Maximum: 0.9974582254143727


6. Create a zero array of size 10 and replace 5th element with 1.


In [ ]:
f = np.zeros(10)
f[4] = 1
print(f)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7. Reverse an array arr = [1,2,0,0,4,0].


In [ ]:
arr = np.array([1,2,0,0,4,0])
print(arr[::-1])

[0 4 0 0 2 1]


8. Create a 2d array with 1 on border and 0 inside.


In [ ]:
g = np.ones((5,5))
g[1:-1,1:-1] = 0
print(g)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


9. Create a 8X8 matrix and fill it with a checkerboard pattern.


In [ ]:
checker = np.zeros((8,8))
checker[1::2, ::2] = 1
checker[::2, 1::2] = 1
print(checker)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


##Problem - 3: Array Operations:


###For the following arrays:

###x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);

###v = np.array([9,10]) and w = np.array([11,12]);

###Complete all the task using numpy:

In [ ]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11,12])

1. Add the two array.


In [ ]:
print(x + y)

[[ 6  8]
 [10 13]]


2. Subtract the two array.


In [ ]:
print(x - y)

[[-4 -4]
 [-4 -3]]


3. Multiply the array with any integers of your choice.


In [ ]:
print(x * 3)

[[ 3  6]
 [ 9 15]]


4. Find the square of each element of the array.


In [ ]:
print(np.square(x))

[[ 1  4]
 [ 9 25]]


5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.


In [ ]:
print("v·w =", np.dot(v,w))
print("x·v =", np.dot(x,v))
print("x·y =", np.dot(x,y))

v·w = 219
x·v = [29 77]
x·y = [[19 22]
 [50 58]]


6. Concatenate x(and)y along row and Concatenate v(and)w along column.

    {Hint:try np.concatenate() or np.vstack() functions.


In [ ]:
print(np.vstack((x,y)))

print("--------------------")

print(np.column_stack((v,w)))

[[1 2]
 [3 5]
 [5 6]
 [7 8]]
--------------------
[[ 9 11]
 [10 12]]


7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?


In [ ]:
np.concatenate((x,v))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

##Problem - 4: Matrix Operations:


###• For the following arrays:

###A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);

###Prove following with Numpy

1. Prove A.A−1 = I.


In [ ]:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

In [ ]:
A_inv = np.linalg.inv(A)      # inverse of A
result = np.dot(A, A_inv)     # A * A^-1

print(result)

[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


2. Prove AB ̸= BA.


In [ ]:
AB = np.dot(A, B)
BA = np.dot(B, A)

print("AB =\n", AB)
print("BA =\n", BA)

AB =
 [[23 13]
 [51 29]]
BA =
 [[36 44]
 [13 16]]


3. Prove (AB)
T = BTAT

In [ ]:
AB = np.dot(A,B)

left = AB.T                 # (AB)^T
right = np.dot(B.T, A.T)    # B^T A^T

print(left)
print(right)

[[23 51]
 [13 29]]
[[23 51]
 [13 29]]


• Solve the following system of Linear equation using Inverse Methods.

  2x − 3y + z = −1

  x − y + 2z = −3

  3x + y − z = 9

  {Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}


In [ ]:
A = np.array([[2,-3,1],
              [1,-1,2],
              [3,1,-1]])

B = np.array([[-1],
              [-3],
              [9]])

A_inv = np.linalg.inv(A)

X = np.dot(A_inv, B)

print(X)

[[ 2.]
 [ 1.]
 [-2.]]


• Now: solve the above equation using np.linalg.inv function.

{Explore more about ”linalg” function of Numpy}


In [ ]:
X = np.linalg.inv(A).dot(B)
print(X)

[[ 2.]
 [ 1.]
 [-2.]]
